name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'qa-*'
      - 'prod-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'dev' || startsWith(github.ref, 'refs/tags/qa-') && 'qa' || 'prod' }}
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Set environment
        run: |
          if [[ "$GITHUB_REF" == refs/heads/main ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == refs/tags/qa-* ]]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          fi
      - name: Write tfvars from environment secret
        run: echo "$TFVARS" > environments/$ENVIRONMENT/terraform.tfvars
        shell: bash
        env:
          TFVARS: ${{ secrets.TFVARS }}
      - name: Initialize
        run: cd environments/$ENVIRONMENT && tofu init -input=false
      - name: Apply
        run: cd environments/$ENVIRONMENT && tofu apply -auto-approve -input=false

