name: Validate

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      TF_BACKEND_BUCKET: ${{ secrets.BACKEND_BUCKET }}
      TF_BACKEND_TABLE: ${{ secrets.BACKEND_DYNAMODB_TABLE }}
    strategy:
      matrix:
        dir: ["environments/dev", "environments/qa", "environments/prod"]
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
      - name: Install Terragrunt
        run: |
          TG_VERSION=0.83.2
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64 -O terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt
      - name: Format Terraform
        run: tofu fmt -check -recursive
      - name: Format Terragrunt
        run: terragrunt hclfmt --terragrunt-check
      - name: Initialize
        run: cd ${{ matrix.dir }} && terragrunt init -backend=false --terragrunt-non-interactive
        env:
          TERRAGRUNT_TFPATH: tofu
      - name: Validate
        run: cd ${{ matrix.dir }} && terragrunt validate --terragrunt-non-interactive
        env:
          TERRAGRUNT_TFPATH: tofu

