name: Validate

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["environments/dev", "environments/qa", "environments/prod"]
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1
      - name: Format
        run: tofu fmt -check -recursive
      - name: Initialize
        run: cd ${{ matrix.dir }} && tofu init -backend=false
      - name: Validate
        run: cd ${{ matrix.dir }} && tofu validate

